Adapt Lisk environment
LiskHQ/scaffold-lisk pull request #1
Opened 2024-08-09 13:59 UTC by clemente-xyz

## Description

We want to update fork this repo, and update to the lisk branded with default network with lisk for the dev-rel effort.

## How was it solved?

- [x] Update the branding
- [x] Update the README
- [x] Update the default network

### How was it tested?

Manually.

2024-08-12 09:30 UTC, shuse2 requested changes
![Screenshot 2024-08-12 at 11 27 11](https://github.com/user-attachments/assets/91eb0138-f22e-4148-946b-986cf66e46b9)

* Links are not working
* Still Optimism logo on the README

2024-08-12 09:30 UTC, shuse2 commented on README.md
> +Scaffold-Lisk is a fork of Scaffold-ETH2 with minimal differences, providing additional dApp examples, native support for Superchain testnets, and more low-level instructions. We highly recommend the
we are forking `Scaffold-OP`

2024-08-12 14:44 UTC, shuse2 requested changes

2024-08-12 14:44 UTC, shuse2 commented on README.md
> +  <a href="https://lisk.com"><img alt="Lisk" src="https://github.com/LiskHQ/scaffold-lisk/blob/main/packages/nextjs/public/readme-banner.png" width="100%"></a>
```suggestion
  <a href="https://lisk.com"><img alt="Lisk" src="./packages/nextjs/public/readme-banner.png" width="100%"></a>
```

2024-08-12 14:44 UTC, shuse2 commented on README.md
> +# Scaffold-Lisk
with above image, it looks redundant

2024-08-12 14:44 UTC, shuse2 commented on README.md
>  </h4>
these are link to the original, since it is mentioned below, we could remove it?

2024-08-14 11:14 UTC, shuse2 approved these changes

2024-08-14 12:38 UTC, ikem-legend approved these changes

2024-08-14 12:39 UTC, merged